project:
  type: website
  output-dir: docs

website:
  title: "BMI/STAT 741 Course Study Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Part I - Univariate Events"
        contents:
          - chapter1.qmd
          - chapter2.qmd
      - section: "Miscellaneous"
       
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: true

editor: visual

