project:
  type: website
  output-dir: docs

website:
  title: "BMI/STAT 741 Course Study Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Part I - Univariate Events"
        contents:
          - chapter1.qmd
          - chapter2.qmd
          - chapter3.qmd
          - chapter4.qmd
          - chapter5.qmd
          - chapter6.qmd
          - chapter7.qmd
      - section: "Part II - Complex Outcomes" 
        contents:
          - chapter8.qmd
          - chapter9.qmd
          - chapter10.qmd
          - chapter11.qmd
      - section: "Miscellaneous"
       
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: true

editor: visual

