---
title: "Syllabus"
---

### Overview

This course provides a survey of modern statistical methodology for the analysis of **censored** time-to-event data arising from clinical, epidemiological, sociological, and engineering studies. We use intuitive explanations of statistical theory, such as counting-process martingale, to deepen understanding of real-world problems and train problem-solving skills. To do so, we combine methodological exposition with extensive case studies, mostly drawn from health sciences research (sample R/SAS code for case studies will be provided). The overall emphasis of this course is on the **application** side of study design and data analysis.

### Course structure

The course is divided into three parts. The first part focuses on methods for univariate event times, e.g., Kaplan—Meier curve, log-rank test, and Cox proportional hazards model. Building on this foundation, the second part expands the scope to complex outcomes such as recurrent or multivariate events, (semi-)competing risks, joint analysis of survival and longitudinal data, multistate data, composite endpoints, and so forth. Special topics for censored data from cutting-edge research areas such as causal inference and machine learning are discussed in the third part.

### Learning outcomes

After taking the course, students will be able to:

-   Understand the features of censored data and their implications in statistical inference

-   Choose proper non- and semi-parametric methods for analysis of various types of data

-   Understand and check the assumptions needed for estimation and inference

-   Implement the inference procedures to solve real-world problems using statistical packages such as R (or SAS)

-   Interpret and present the analytic results clearly and coherently to answer substantive questions

### Prerequisites

Students are expected to have basic knowledge in statistical concepts such as random variables, expectation, variance, and maximum likelihood estimation, and to have taken first courses in statistical hypothesis testing (e.g., *t*-test, ANOVA, etc.) and (generalized) linear regression models. Prior experience with R or SAS is helpful but not required.

### Time and Location

MW 2:30—3:45pm; 1220 HSLC (Health Sciences Learning Center)

### Instructors

#### Main Instructor

Lu Mao, PhD

WARF 207A, 610 Walnut St, Madison, WI 53726

Email: lmao\@biostat.wisc.edu

Phone: 608-263-5674

Office Time and Location: T&Th 3--4pm, or by appointment.

Zoom link provided in syllabus on Canvas.

#### Teaching Assistant

Po-Kuei Chen (pchen299\@wisc.edu); Office hours:

-   Monday 4:30--5:30pm (Medical Science Center (MSC), room B248)

-   Wednesday 4:30--5:30pm (Zoom link provided in syllabus on Canvas)

-   By appointment.

### Readings

-   \[**Required**\] *Applied Survival Analysis: From Univariate to Complex Time-to-Event Outcomes* (To be posted periodically by chapter on Canvas)

-   \[For methodological reader\] Kalbfleisch, J. D. & Prentice, R. L. (2002). *The statistical analysis of failure time data* (2^nd^ Ed). John Wiley & Sons.

-   \[For applied reader\] Klein, J. P. & Moeschberger, M. L. (2003). *Survival analysis: techniques for censored and truncated data* (2^nd^ Ed). Springer Science & Business Media.

-   \[More theoretical\] Fleming, T. R. & Harrington, D. P. (1991). *Counting processes and survival analysis*. John Wiley & Sons.

### Course Schedule

**Kickoff**

|      |         |          |
|------|---------|----------|
| 1/24 | Lecture | Overview |
|      | Reading | Syllabus |

**Part I: Univariate Events**

|      |         |                                                                              |
|-----------|-----------|---------------------------------------------------|
| 1/29 | Lecture | Introduction                                                                 |
|      | Reading | Chapter 1                                                                    |
| 1/31 | Lecture | Mathematical Foundations                                                     |
|      | Reading | Chapter 2                                                                    |
| 2/5  | Lecture | Nonparametric Estimation of the Survival Curve                               |
|      | Reading | Chapter 3                                                                    |
| 2/7  | Lecture | Comparing Survival Rates between Groups                                      |
|      | Reading | Chapter 3                                                                    |
| 2/12 | Lecture | The Cox Proportional Hazards Model – [Assumptions and Inference]{.smallcaps} |
|      | Reading | Chapter 4                                                                    |
| 2/14 | Lecture | The Cox Proportional Hazards Model – [Residual Analysis]{.smallcaps}         |
|      | Reading | Chapter 4                                                                    |
| 2/19 | Lecture | The Cox Proportional Hazards Model – [Time-Varying Covariates]{.smallcaps}   |
|      | Reading | Chapter 4                                                                    |
| 2/21 | Lecture | Other Non- and Semi-parametric Methods                                       |
|      | Reading | Chapter 5                                                                    |
| 2/26 | Lecture | Study Design and Sample Size Calculation                                     |
|      | Reading | Chapter 6                                                                    |
| 2/28 | Lecture | Left Truncation                                                              |
|      | Reading | Chapter 7                                                                    |
| 3/4  | Lecture | Interval Censoring                                                           |
|      | Reading | Chapter 7                                                                    |

**Part II: Complex Outcomes**

|      |           |                                                                          |
|-----------|-----------|--------------------------------------------------|
| 3/6  | Lecture   | Multivariate Events – [Conditional (Frailty) Models]{.smallcaps}         |
|      | Reading   | Chapter 8                                                                |
| 3/11 | Lecture   | Multivariate Event Times – [Marginal Models]{.smallcaps}                 |
|      | Reading   | Chapter 8                                                                |
| 3/13 | Lecture   | Recurrent Event                                                          |
|      | Reading   | Chapter 9                                                                |
| 3/18 | Lecture   | Competing and Semi-competing Risks                                       |
|      | Reading   | Chapter 10                                                               |
| 3/20 | Lecture   | Joint Analysis of Longitudinal and Survival Data                         |
|      | Reading   | Chapter 11                                                               |
| 4/1  | Lecture   | Multistate Models – [Introduction]{.smallcaps}                           |
|      | Reading   | Chapter 12                                                               |
| 4/3  | Lecture   | Multistate Models – [Cox-Type Markov and Semi-Markov Models]{.smallcaps} |
|      | Reading   | Chapter 12                                                               |
| 4/8  | Lecture\* | Composite Endpoints – [Nonparametric Estimation]{.smallcaps}             |
|      | Reading   | Chapter 13                                                               |
| 4/10 | Lecture   | Composite Endpoints – [Semiparametric Regression]{.smallcaps}            |
|      | Reading   | Chapter 13                                                               |

**Part III: Special Topics**

|      |         |                                                                                |
|-----------|-----------|---------------------------------------------------|
| 4/15 | Lecture | Causal Inference with Censored Data – [IPTW and Standardization]{.smallcaps}   |
|      | Reading | Chapter 14                                                                     |
| 4/17 | Lecture | Causal Inference with Censored Data – [Marginal Structural Models]{.smallcaps} |
|      | Reading | Chapter 14                                                                     |
| 4/22 | Lecture | Machine Learning with Censored Data – [Variable Selection]{.smallcaps}         |
|      | Reading | Chapter 15                                                                     |
| 4/24 | Lecture | Machine Learning with Censored Data – [Nonlinear Regression]{.smallcaps}       |
|      | Reading | Chapter 15                                                                     |
| 4/29 | Lecture | Guest Lecture (Dave DeMets or other)                                           |
| 5/1  | Lecture | Recap                                                                          |

\* Possibly online due to the instructor attending an FDA conference (<https://www.advamed.org/events/fda-advamed-mdsi-conference>).

### Homework and Exams

One homework every other week; one mid-term, and one data analysis final project.

### Grading

15% attendance; 35% homework; 20% mid-term; 30% final project.
