---
title: "Chapter 1 - Introduction"
execute: 
  warning: false
  cache: true
---

### Slides

Lecture slides [here](chap1.html){target="_blank"}. (To convert html to pdf, press E $\to$ Print $\to$ Destination: Save to pdf)

### Base R Code

```{r}
#| code-fold: true
#| code-summary: "Show the code"
#| eval: false



###########################################################################
# The following code generates Figure 1.2 and Table 1.11 of chapter 1.   ##
###########################################################################

####################################################
# Figure 1.2                   
# Proper and improper estimates of survival function
####################################################

## read in the GBC mortality data
data <- read.table("Data//German Breast Cancer Study//gbc_mort.txt")

head(data)

# load the survival package needed for Kaplan--Meier curves
library(survival)


#subset data by hormone==1, 2
data1 <- data[data$hormone==1,]
data2 <- data[data$hormone==2,]

# fit group-specific Kaplan--Meier curves
KMfit1 <- survfit(Surv(time,status)~1,data=data1)
KMfit2 <- survfit(Surv(time,status)~1,data=data2)


# Define a function to calculate empirical survival curve
# Argument: x= a vector containing a sample of real numbers
# Output:   t= order unique values of x
#           S =survival probability as a function of t
emp.surv <- function(x){
  n <- length(x)
  t <- sort(unique(x))
  m <- length(t)
  S <- rep(NA,m)
  for (i in 1:m){
    S[i] <- sum(x>t[i])/n
  }
  return(list(t=t,S=S))
}


## event imputation##

obj1.imp <- emp.surv(data1$time)
obj2.imp <- emp.surv(data2$time)

## complete case
obj1.cc <- emp.surv(data1$time[data1$status==1])
obj2.cc <- emp.surv(data2$time[data2$status==1])


## plot KM, event imputed, and complete-case survival curves
par(mfrow=c(1,2))

plot(KMfit1,conf.int=F,cex.axis=1.5,cex.lab=1.5,cex.main=1.5,
     xlab="Time (months)",ylab="Survival rate",
     main="No Hormone",lwd=2)
lines(obj1.imp$t,obj1.imp$S,lty=2,lwd=2)
lines(obj1.cc$t,obj1.cc$S,lty=3,lwd=2)

plot(KMfit2,conf.int=F,cex.axis=1.5,cex.lab=1.5,cex.main=1.5,
     xlab="Time (months)",ylab="Survival rate",
     main="Hormone",lwd=2)
lines(obj2.imp$t,obj2.imp$S,lty=2,lwd=2)
lines(obj2.cc$t,obj2.cc$S,lty=3,lwd=2)

############################################################################



###########################################################
# Table 1.11. Patient characteristics for the GBC study
###########################################################


##A function calculating median (IQR) by 
## binary group
## Input: y=quantitative variable
##        trt=binary group variable
##        decp=number of decimal points
## Output: a row vector containing median (IQR)
##    by the two levels of trt and overall 

Mean.IQR.by.trt <- function(y,trt,decp=1){
  groups <- sort(unique(trt))
  all <- quantile(y)
  g1 <- quantile(y[trt==groups[1]])
  g2 <- quantile(y[trt==groups[2]])
  
  result <- matrix(NA,1,3)
  colnames(result) <- c(groups,"Overall")
  result[1,1] <- paste0(round(g1[3],decp)," (",round(g1[2],decp),", ",round(g1[4],decp),")")
  result[1,2] <- paste0(round(g2[3],decp)," (",round(g2[2],decp),", ",round(g2[4],decp),")")
  result[1,3] <- paste0(round(all[3],decp)," (",round(all[2],decp),", ",round(all[4],decp),")")
  return(result)
}


##A function calculating N (%) by 
## binary group
## Input: x=categorical variable with p levels
##        trt=binary group variable
##        decp=number of decimal points of %
## Output: a p x 3 matrix containing N (%) for each level of x
##    by the two levels of trt and overall 
N.prct.by.trt <- function(x,trt,decp=1){
  groups <- sort(unique(trt))
  x.levels <- sort(unique(x))
  p <- length(x.levels)
  n <- length(x)
  n1 <- length(x[trt==groups[1]])
  n2 <- length(x[trt==groups[2]])
  
  result <- matrix(NA,p,3)
  colnames(result) <- c(groups,"Overall")
  rownames(result) <- x.levels
  
  for (i in 1:p){
    n1i <- sum(x[trt==groups[1]]==x.levels[i])
    n2i <- sum(x[trt==groups[2]]==x.levels[i])
    ni <- sum(x==x.levels[i])
    
    
  result[i,1] <- paste0(n1i," (",round(n1i/n1*100,decp),"%)")
  result[i,2] <- paste0(n2i," (",round(n2i/n2*100,decp),"%)")
  result[i,3] <- paste0(ni," (",round(ni/n*100,decp),"%)")
  }
  
  
  return(result)
}


##Baseline characteristics by hormonal group:
## age (years), menopause, tumor size (mm), tumor grade
## number of nodes, progesterone receptors content (fmol/mg),
## and estrogen receptors content (fmol/mg)
table1 <- rbind(
  Mean.IQR.by.trt(y=data$age,trt=data$hormone),
  N.prct.by.trt(x=data$meno,trt=data$hormone),
  Mean.IQR.by.trt(y=data$size,trt=data$hormone),
  N.prct.by.trt(x=data$grade,trt=data$hormone),
  Mean.IQR.by.trt(y=data$nodes,trt=data$hormone),
  Mean.IQR.by.trt(y=data$prog,trt=data$hormone),
  Mean.IQR.by.trt(y=data$estrg,trt=data$hormone)
  
)


noquote(table1)

#########################################
# Calculate the event rates (per year)  #
#########################################

#############################
#  Death rate               #
#############################


# Numerator: total # of events
# (N of events is sum of status variable)
num.D <- c(sum(data$status[data$hormone==1]), 
        sum(data$status[data$hormone==2]), 
        sum(data$status))

# Denominator: total length of follow-up (year)
denom.D <- c(sum(data$time[data$hormone==1]), 
        sum(data$time[data$hormone==2]), 
        sum(data$time))/12

# Death rate
round(num.D/denom.D,3)

#############################
# Composite event rate      #
#############################

# Read in the complete data
gbc <- read.table("Data//German Breast Cancer Study//gbc.txt")

# subset to first-event data
# Sort the data by time within each id
o <- order(gbc$id,gbc$time)
gbc <- gbc[o,]
#get the first row for each id
data.CE <- gbc[!duplicated(gbc$id),]

# Numerator: total # of events
# an event means (status>0)
num.CE <- c(sum(data.CE$status[data.CE$hormone==1]>0), 
        sum(data.CE$status[data.CE$hormone==2]>0), 
        sum(data.CE$status>0))

# Denominator: total length of follow-up (year)
denom.CE <- c(sum(data.CE$time[data.CE$hormone==1]), 
          sum(data.CE$time[data.CE$hormone==2]), 
          sum(data.CE$time))/12


#CE rate
round(num.CE/denom.CE,3)

```

### Tidyverse Solutions

#### Data cleaning

```{r}
#| fig-width: 6
#| fig-height: 4
#| fig-align: center



library(tidyverse)
library(survival)

## read in the GBC mortality data
data <- read.table("Data//German Breast Cancer Study//gbc_mort.txt")

head(data)

obj <- summary(survfit(Surv(time, status) ~ hormone, data))

km <- tibble(
  t = obj$time,
  surv = obj$surv,
  hormone = parse_number(as.character(obj$strata)),
  type = "Kaplan-Meier"
) |> 
  add_row(
    t = c(0, 0),
    surv = c(1, 1),
    hormone = 1:2,
    type = "Kaplan-Meier"
  )


## empirical survival function

# event imputation
imp <- data |> 
  group_by(
    hormone
  ) |> 
  reframe(
    t = time,
    surv = 1- ecdf(time)(time)
  ) |> 
  arrange( # order by time
    t
  ) |> 
  mutate(
    type = "Event-imputation"
  )


cc <- data |> 
  filter(
    status == 1
  ) |> 
  group_by(
    hormone
  ) |> 
  reframe(
    t = time,
    surv = 1- ecdf(time)(time)
  ) |> 
  arrange( # order by time
    t
  ) |> 
  mutate(
    type = "Complete-case"
  )


hormone_labeller <- c("1" = "No Hormone", "2" = "Hormone")

km |> 
  add_row(imp) |> 
  add_row(cc) |> 
  mutate(
    type = fct(type)
  ) |> 
  ggplot(aes(x = t, y = surv, linetype = type)) +
  geom_step() +
  facet_wrap( ~ hormone, labeller = labeller(hormone = hormone_labeller)) +
  theme_bw() +
  scale_x_continuous(name = "Time (months)", breaks = seq(0, 72, by = 12), limits = c(0, 72)) +
  scale_y_continuous(name = "Survival rate", limits = c(0, 1)) +
  scale_linetype_manual(name = "Estimator",
                        values = 1:3) +
  theme(
    legend.position = "bottom"
  )
  
```

#### ggplotting Figure 1.2

#### Table one
