---
title: "Chapter 7 - Left Truncation and Interval Censoring"
---

## Slides

Lecture slides [here](chap7.html){target="_blank"}. (To convert html to pdf, press E $\to$ Print $\to$ Destination: Save to pdf)

## Base R Code

```{r}
#| code-fold: true
#| code-summary: "Show the code"
#| eval: false

##################################################################
# This code generates all numerical results in chapter 7.      ##
##################################################################

library(survival)

# read in the Channing study data
channing <- read.table("Data\\Channing House Study\\channing.txt")

head(channing)


# fit a Cox model to the Channing study data
# with entry age as left-truncation time
obj <- coxph(Surv(Entry.Age, End.Age, status) ~ factor(gender), data=channing)

summary(obj)




## BMA HIV study
## Bangkok Metropolitan Administration HIV Study
data <- read.table("Data//Bangkok Metropolitan Administration HIV_AIDS Study//bam.txt")


# install the IntCens package from local file
install.packages("IntCens_0.1.0.tar.gz",
                 repos = NULL,
                 type = "source")
library(IntCens)

## BMA data
head(data)

# get the response data for ICSurvICM()
delta <- data$delta
gamma <- data$gamma
n <- nrow(data)
U <- data$U
V <- data$V


# Fit a proportional hazards model
obj.PH <- ICSurvICM(delta,gamma,U,V,Z = data[,5:9],model="PH")
print.ICSurv(obj.PH)


# obj.PO <- ICSurvICM(delta,gamma,U,V,Z=data[,5:9],model="PO")


# Table 7.3
# construct a table for hazard ratio and
# 95% confidence intervals

#regression parameter
beta <- obj.PH$beta
se <- sqrt(diag(obj.PH$var))
c1 <- round(exp(beta),2)
c2 <- paste0("(",round(exp(beta-1.96*se),2),", ",
   round(exp(beta+1.96*se),2),")")
noquote(cbind(c1,c2))



# Prediction of HIV sero-negative probabilities for a median-aged male IDU
# without histories of needle sharing or drug injection in jail by prior imprisonment
# status.
par(mfrow=c(1,1))
age.med <- median(data[,"age"])
plot.ICSurv(obj.PH, z=c(age.med,1,0,0,0),xlim=c(0,50), lty = 2,
     xlab="Time (months)",ylab="HIV sero-negative probabilities",
     lwd=2, main = "")
plot.ICSurv(obj.PH, z=c(age.med,1,0,1,0), xlim=c(0,50), add=T,
     lwd=2)
legend(0, 0.3, lty=c(2, 1), c("Not jailed before","Jailed before"), lwd=2)

```

## Follow-up Plots

### Under left truncation

```{r}

library(tidyverse)
# read in the Channing study data
channing <- read.table("Data\\Channing House Study\\channing.txt")

head(channing)


set.seed(2024)
channing_f_sub <- channing |> 
  filter(gender == 2) |> 
  sample_n(100)


channing_m_sub <- channing |> 
  filter(gender == 1) 


channing_sub <- channing_f_sub |> add_row(channing_m_sub)
n <- nrow(channing_sub)


gender_labeller <- c("1" = "Males", "2" = "Females")

chan_fig <- channing_sub |> 
  add_column(ID = 1 : n) |> 
  ggplot(aes(y = reorder(ID, End.Age))) +
  geom_linerange(aes(xmin = Entry.Age, xmax = End.Age)) +
  geom_point(aes(x = Entry.Age, shape = "2"), fill = "white", size = 2) +
  geom_point(aes(x = End.Age, shape = factor(status)), fill = "white", size = 2)  + 
  geom_vline(xintercept = 60, linewidth = 1) +
  facet_wrap(~ gender, ncol = 2, scales = "free", 
             labeller = labeller(gender = gender_labeller)) +
  theme_minimal() +
  scale_y_discrete(name = "Subjects") +
  scale_x_continuous(name = "Age (years)", limits = c(60, 100), 
                     breaks = seq(60, 100, by = 10), 
                     expand = expansion(c(0, 0.05)))  +
  scale_shape_manual(limits = c("2", "0", "1"),  values = c(22, 23, 19), 
                      labels = c("Admission", "Censoring", "Death")) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.text = element_text(size = 11),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    strip.text = element_text(size = 10)
  )

# ggsave("trunc_chan_fig.pdf", chan_fig, width = 8, height = 9)
# ggsave("trunc_chan_fig.eps", chan_fig, width = 8, height = 9)

```


### Under interval-censoring

```{r}
library(IntCens)

bma <- data

n <- nrow(bma)

bma_lr <- bma |> 
  mutate(
    ID = 1: n, 
    L = case_when(
      delta == 1 ~ 0,
      gamma == 1 ~ U,
      (delta + gamma == 0) ~ V
    ),
    R = case_when(
      delta == 1 ~ U,
      gamma == 1 ~ V,
      (delta + gamma == 0) ~ Inf
    ),
    .before = 1
  )


set.seed(2024229)


bma_lr_jail_sub <- bma_lr |> 
  filter(jail == 1) |> 
  sample_n(150) 
  
bma_lr_nojail_sub <- bma_lr |> 
  filter(jail == 0) |> 
  sample_n(150) 

bma_lr_sub <- bma_lr_jail_sub |> 
  add_row(bma_lr_nojail_sub) |> 
  mutate(
    end = ifelse(R == Inf, L, R),
    status = (R < Inf) + 0
  )

nrow(bma_lr_sub)


jail_labeller <- c("0" = "No imprisonment", "1" = "Imprisonment")

bma_fig <- bma_lr_sub |> 
  ggplot(aes(y = reorder(factor(ID), end))) +
  geom_linerange(aes(xmin = 0, xmax = L), alpha = 0.3) +
  geom_linerange(data = bma_lr_sub |> filter(status == 1),
    aes(xmin = L, xmax = R), linetype = 1) +
  geom_point(data = bma_lr_sub |> filter(status == 1), aes(x = L, shape = "1"), size = 2) +
  geom_point(data = bma_lr_sub |> filter(status == 1), aes(x = R, shape = "1"), size = 2) +
  geom_point(data = bma_lr_sub |> filter(status == 0), aes(x = L, shape = "0"), 
             fill = "white", size = 2) +
  geom_vline(xintercept = 0) +
  facet_wrap(~ jail, scales = "free", labeller = labeller(jail = jail_labeller)) +
  theme_minimal() +
  scale_y_discrete(name = "Subjects") +
  scale_x_continuous(name = "Time (months)", 
                     breaks = seq(0, 48, by = 6), 
                     expand = expansion(c(0, 0.05))) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) + 
  scale_shape_manual(limits = c("0", "1"),  values = c(23, 19), 
                      labels = c("Right censoring", "L-R containing seroconversion")) +
 theme(
    legend.position = "top",
    legend.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.text = element_text(size = 11),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    strip.text = element_text(size = 10)
  )


ggsave("trunc_bma_fig.pdf", bma_fig, width = 8, height = 12)
ggsave("trunc_bma_fig.eps", bma_fig, width = 8, height = 12, device = cairo_pdf)
```






