---
title: "10-Minute In-Class Quiz 2: Survival Analysis (Chapters 4–7)"
format: pdf
execute:
  echo: false
  warning: false
---

## **Instructions**

-   You have **10 minutes** to complete this quiz.
-   Answer all questions *concisely*.
-   Show all relevant calculations where applicable.

## **Question 1 (5 points) – Left-Truncated Data**

The table below presents left-truncated survival data for **6 individuals** in a study.

ID| Entry Time $T_L$ | Event/Censoring Time $X$ | Event Indicator $\delta$ (1: event; 0: censoring) |
|:--------------------:|:--------------------:|:------------------:|:-----------------------------:|
1| 0 | 2.2 | 1 |
2| 1.5 | 3.8 | 0 |
3| 1.8 | 4.1 | 1 |
4| 3.0 | 6.3 | 0 |
5| 3.5 | 7.0 | 1 |
6| 5.0 | 8.0 | 1 |




-   Compute the Kaplan-Meier estimator $\hat{S}(t)$ at times $t = 2, 4, 6.5$, and $8$. (Expressions are sufficient; no need to compute numerical values.)

**Solution:** 
The unique event times are $t_1 = 2.2$, $t_2 = 4.1$, $t_3 = 7.0$, and $t_4 = 8.0$. 

-   At $t_1 = 2.2$, there are $n_j=3$ (ID = 1, 2, 3) subjects at risk and $d_j = 1$ failure;
-   At $t_2 = 4.1$, there are $n_j=3$ (ID = 3, 4, 5) subjects at risk and $d_j = 1$ failure;
-   At $t_3 = 7.0$, there are $n_j=2$ (ID = 5, 6) subjects at risk and $d_j = 1$ failure;
-   At $t_4 = 8.0$, there is $n_j=1$ (ID = 6) subject at risk and $d_j = 1$ failure.


\begin{table}[h]
    \centering
    \caption{Survival probabilities at observed time points.}
    \begin{tabular}{cccc}
        \hline
        $t_j$ & $d_j$ & $n_j$ & $S(t_j)=\prod_{l=1}^j(1-d_l/n_l)$ \\
        \hline
        2.2 & 1 & 3 & 0.667 \\
        4.1 & 1 & 3 & 0.444 \\
        7.0 & 1 & 2 & 0.222 \\
        8.0 & 1 & 1 & 0.000 \\
        \hline
    \end{tabular}
    
\end{table}

From Table 2, $\hat S(2) = 1$, $\hat S(4) = 0.667$, $\hat S(6.5) = 0.444$, and $\hat S(8) = 0$.



## **Question 2 (5 points) – Time-Varying Treatment Effect in Cox Model**

Consider a Cox proportional hazards model: \begin{equation}\label{eq:cox}
\lambda(t \mid Z) = \lambda_0(t) \exp(\beta Z),
\end{equation} where $Z$ is a binary treatment indicator ($Z = 1$ for treatment, $Z = 0$ for control).

Now suppose the log-hazard ratio is not constant over time, but follows a **quadratic function**: $$
\text{HR}(t) = \frac{\lambda(t \mid Z=1)}{\lambda(t \mid Z=0)} = \gamma_0 + \gamma_1 t + \gamma_2 t^2.
$$

-   To specify the above form of HR$(t)$, add time-varying covariates in model \eqref{eq:cox} that are interactions between $Z$ and certain functions of time.

**Solution:** 

Set

$$
\lambda(t \mid Z) = \lambda_0(t) \exp\{Z\log(\gamma_0 + \gamma_1 t + \gamma_2 t^2)\},
$$
then
$$
\text{HR}(t) = \frac{\lambda_0(t) \exp\{\log(\gamma_0 + \gamma_1 t + \gamma_2 t^2)\}}{\lambda_0(t)} = \gamma_0 + \gamma_1 t + \gamma_2 t^2.
$$
However, this will be a non-standard Cox model.